### PR TITLE
feature: Add commandWillExecute signal to CommandRegistry

### PR DESCRIPTION
**Pull request by thomasjm**
This signal would be useful to me.

Note: it looks like I need to update `review/api/commands.api.md` but I couldn't figure out how to do it.

### CODE REVIEW

**Review by blink1073 — COMMENTED** [review]
The changestream entries are automated, mind removing this for now?

**Comment by blink1073** [comment]
@thomasjm, thanks for this!  We're not maintaining the `review/api/` folder, since we're blocked by an upstream issue.

**Comment by blink1073** [comment]
@fcollonval @jtpio thoughts on this one?

**Comment by jasongrout** [comment]
Can we list some usecases where this signal would be important?

**Comment by thomasjm** [comment]
For me, it would help to implement a command palette modal similar to the one in VSCode. I want to be able to know a command is about to be executed so I can take UI actions first (for example, closing the modal).

FWIW, another solution would be to add a signal or similar directly to the `CommandPalette` to announce when a command is about to be executed.

It's possible I can get this to work by just subclassing the `CommandRegistry`, let me try that first...

**Comment by thomasjm** [comment]
BTW, I was able to do what I wanted by subclassing so you can close this if you like. Thanks!

**Comment by blink1073** [comment]
Great, less API is better!

**Pull request closed without merging**
