### PR TITLE
Allow commands to accept partial json objects

### PR DESCRIPTION
**Pull request by blink1073**

### CODE REVIEW

**Comment by blink1073** [comment]
I don't see any downside.

**Comment by blink1073** [comment]
Published `commands@1.9.0`

**Comment by vidartf** [comment]
This should probably be update as well then:

https://github.com/jupyterlab/lumino/blob/4030e959710d64892a6da59bb2fa7df8f3fa48d9/packages/widgets/src/menu.ts#L990

**Comment by vidartf** [comment]
Note: I think this might break compilation of command implementor code.

**Comment by vidartf** [comment]
e.g.
```ts
// ...
execute: args => {
  return args['foo'].toString();
}
// ...

**Pull request merged**
