### PR TITLE
Disable text eliding by default

### PR DESCRIPTION
**Pull request by ibdafna**
Addresses #448

### CODE REVIEW

**Review by fcollonval — COMMENTED** [review]
Thanks @ibdafna could you run `yarn api` to make the CI check happy :wink: ?

Does it solves the issue or should we let the issue opened?

**Comment by krassowski** [comment]
I would say that this does not fix the issue, since we can make vast algorithmic improvements (and even keep eliding enabled by default if we do that). While, it certainly helps to be able to disable eliding, ideally it could be disabled/enabled on per-column basis.

**Comment by ibdafna** [comment]
@krassowski This is a good start, and it does address the issue. We can open separate PRs for improving the algorithms of text eliding and wrapping. But I'd like to iterate again, there is no easy way to significantly reduce the time elide takes as it needs to make at least one call per cell to the measureText function. You can certainly enable or disable this on a per column basis by setting a custom TextRenderer for columns you want it enabled or disabled for.

**Comment by ibdafna** [comment]
@fcollonval `yarn api` doesn't generate any file changes?

**Comment by fcollonval** [comment]
> yarn api doesn't generate any file changes?

I don't know if you did [cacc6ac](https://github.com/jupyterlab/lumino/pull/451/commits/cacc6ac2c0097cc5ba538989b15e68ae9e60618f) manually then (thanks for that). But I think the remaining error was a typo in that commit. I fixed it. :crossed_fingers: for the CI

**Pull request merged**
