### PR TITLE
chore(Widget):  Simplify attach/detach sanity checking

### PR DESCRIPTION
**Pull request by GordonSmith**
Also makes compatible with shadowDom

Signed-off-by: Gordon Smith <GordonJSmith@gmail.com>

### CODE REVIEW

**Review by fcollonval — APPROVED** [review]
Thanks @GordonSmith 

Out of curiosity do you know if the `isConnected` is faster than contains?

> caniuse [report 93%](https://caniuse.com/?search=isConnected) for that feature.

**Comment by GordonSmith** [comment]
@fcollonval I don't know if it is faster, but realistically it couldn't be slower? (not that it matters as this is test is prior modifiying  items in the DOM which will cause reflow etc. which will be orders of magnitudes slower than either...)
Also worth noting that the "contains" test fails for shadowDom elements...

**Comment by fcollonval** [comment]
> I don't know if it is faster, but realistically it couldn't be slower?

Definitely not - it was purely for my information. I support at 100% what you are doing; I really think that moving to web components would be a great way forward to increase interest in Lumino widgets.

> Note2: It is not supported by ie11 if that is an issue?

No it is not an issue. As I checked support by browsers, I added a link if people are wondering.

**Review by blink1073 — APPROVED** [review]
Thank you!

**Pull request merged**
