### PR TITLE
chore(tsconfig): Correct JSON Schema warnings

### PR DESCRIPTION
**Pull request by GordonSmith**
Signed-off-by: Gordon Smith <gordonjsmith@gmail.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
Pedantic changes to adhere to the formal tsconfig json schema.

**Comment by afshin** [comment]
Could you please show the warnings this fixes?

What command generated the warnings you're referencing?

**Comment by GordonSmith** [comment]
I suspect they become warnings in the future with a newer TS compiler - I will be re-testing with TSC 3.6.x later today and will let you know.

**Comment by GordonSmith** [comment]
Weird - I was only seeing those warnings with TSC 3.5 but not with 3.6.  Closing...

**Pull request closed without merging**
