### PR TITLE
fix(messaging): Remove non standard functions (setImmediate, clearImm…

### PR DESCRIPTION
**Pull request by GordonSmith**
…ediate)

Remove non standard set/clear Immediate and replace them with an animationFrame polyfill

Signed-off-by: Gordon Smith <gordonjsmith@gmail.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
Depending on what browsers you support, there may be no need for the polyfill at all (IOW you could assume that requiestAnimationFrame always exists)?

**Comment by afshin** [comment]
The `@lumino/messaging` library is meant to support `node` as well. It is not browser-only, so the logic ought to remain as is.

**Comment by GordonSmith** [comment]
@afshin just to clarify, your closing because:
* All browsers have adequate `requestAnimationFrame` support
* If `requestAnimationFrame` is absent, your assuming its a NodeJS environment and setImmediate is known to exist
?

**Comment by afshin** [comment]
Yes, the browsers Lumino supports have `requestAnimationFrame` and the only other environment we currently expect this library to run in is `node`, which has `setImmediate` defined.

**Comment by GordonSmith** [comment]
Ok - works for me (FYI you will start to get TS syntax errors in the future - but a ts-ignore and suitable comment should be fine...)

**Comment by afshin** [comment]
Can we add `node` to the `lib` array in `tsconfig.json` to resolve that when it arises?

**Comment by GordonSmith** [comment]
Probably - but not with the current TS compiler version. (I will test later today - slowly working through my forks diffs).
FYI you won't be able to upgrade the TS compiler to 3.7.x due to:  https://github.com/microsoft/TypeScript/issues/33939

**Comment by afshin** [comment]
Cool, thank you!

**Comment by GordonSmith** [comment]
Looks like there isn't a specific ts lib option for this.  We can continue this discussion when I issue a PR for TSC 3.6.4

**Comment by afshin** [comment]
Cheers!

**Pull request closed without merging**
