### PR TITLE
Revert "chore(build): Bump Typescript to 3.9.2"

### LINKED ISSUE #83: [Critical Bug] Changes to `JSONObject` in coreutils@1.5.1 are breaking jupyterlab extension builds
If I try to build the latest master of [jupyter-fs](https://github.com/jpmorganchase/jupyter-fs):

```
git clone git@github.com:jpmorganchase/jupyter-fs.git
cd jupyter-fs
make js
```

I get the following error on the `tsc` (ie typescript compilation) step:

```
$ tsc
../node_modules/@jupyterlab/observables/lib/modeldb.d.ts:227:9 - error TS2416: Property 'changed' in type 'ObservableValue' is not assignable to the same property in base type 'IObservableValue'.
  Type 'ISignal<this, IChangedArgs>' is not assignable to type 'ISignal<IObservableValue, IChangedArgs>'.
    Type 'this' is not assignable to type 'IObservableValue'.
      Type 'ObservableValue' is not assignable to type 'IObservableValue'.
        The types returned by 'get()' are incompatible between these types.
          Type 'JSONValue' is not assignable to type 'PartialJSONValue'.
            Type 'JSONObject' is not assignable to type 'PartialJSONValue'.
              Type 'JSONObject' is not assignable to type 'string'.

227     get changed(): ISignal<this, ObservableValue.IChangedArgs>;
            ~~~~~~~

../node_modules/@jupyterlab/observables/lib/modeldb.d.ts:231:5 - error TS2416: Property 'get' in type 'ObservableValue' is not assignable to the same property in base type 'IObservableValue'.
  Type '() => JSONValue' is not assignable to type '() => PartialJSONValue'.

231     get(): JSONValue;
        ~~~


Found 2 errors.
```

This is definitely being caused by the latest release of `@lumino/coreutils`, since if I add a resolution to the previous `coreutils` to my `package.json`:

```
    "resolutions": {
        "@lumino/coreutils": "1.5.0"
    }
```

the build error is fixed.

I beleive the underlying cause is the [redefintion of `JSONObject`](https://github.com/jupyterlab/lumino/commit/36debf6f5e367dea8f4019e988b2d411f65bbf57#diff-a5ee7256fc82e758380d3477453ddc47R30) that was part of the 1.5.1 release.

@lumino/coreutils@1.5.0:

https://github.com/jupyterlab/lumino/blob/00ae44153f4362f9892624a22d21f486017d488f/packages/coreutils/src/json.ts#L26-L30

@lumino/coreutils@1.5.1:

https://github.com/jupyterlab/lumino/blob/36debf6f5e367dea8f4019e988b2d411f65bbf57/packages/coreutils/src/json.ts#L26-L30

Because this was a patch release of coretuils (1.5.0 => 1.5.1), you'll likely only see the bug if you delete your `yarn.lock` (or if start from a fresh build that never had one).

### PR DESCRIPTION
**Pull request by telamonian**
- fixes #83

This reverts commit 36debf6f5e367dea8f4019e988b2d411f65bbf57.

### CODE REVIEW

**Comment by blink1073** [comment]
I'll merge and release in the morning

**Comment by GordonSmith** [comment]
I believe this all stems from a breaking change in the TypeScript language specification for unions and intersections - specifically this one:  https://github.com/microsoft/TypeScript/wiki/Breaking-Changes#stricter-checks-on-intersections-and-optional-properties 

I haven't looked at what broke in the dependent code - but it may be a matter of adding `Partial<xxx>` in the broken code.  

FWIW some of the base types in the Lumino messaging library are simply wrong with the latest compiler (they end up evaluating to `{}`).

@telamonian - can I suggest you add some new unit tests which replicate the issues you hit and I can take a another look to see if there is a more "flexible" fix?

**Comment by blink1073** [comment]
@GordonSmith I am going to release a patch with this fix to unstick the majority of folks and then we can find a new path forward.

**Comment by blink1073** [comment]
For now you can pin to the exact version that has TS 3.9.

**Comment by blink1073** [comment]
Here are the transitions:

 - @lumino/example-datagrid: 0.6.0 => 0.6.1 (private)
 - @lumino/example-datastore: 0.3.1 => 0.3.2 (private)
 - @lumino/example-dockpanel: 0.3.1 => 0.3.2 (private)
 - @lumino/algorithm: 1.3.1 => 1.3.2
 - @lumino/application: 1.10.1 => 1.10.2
 - @lumino/collections: 1.3.1 => 1.3.2
 - @lumino/commands: 1.11.1 => 1.11.2
 - @lumino/coreutils: 1.5.1 => 1.5.2
 - @lumino/datagrid: 0.9.0 => 0.9.1
 - @lumino/datastore: 0.10.1 => 0.10.2
 - @lumino/default-theme: 0.4.1 => 0.4.2
 - @lumino/disposable: 1.4.1 => 1.4.2
 - @lumino/domutils: 1.2.1 => 1.2.2
 - @lumino/dragdrop: 1.6.1 => 1.6.2
 - @lumino/keyboard: 1.2.1 => 1.2.2
 - @lumino/messaging: 1.4.1 => 1.4.2
 - @lumino/polling: 1.3.1 => 1.3.2
 - @lumino/properties: 1.2.1 => 1.2.2
 - @lumino/signaling: 1.4.1 => 1.4.2
 - @lumino/virtualdom: 1.7.1 => 1.7.2
 - @lumino/widgets: 1.13.1 => 1.13.2

**Comment by blink1073** [comment]
published

**Pull request merged**
