### PR TITLE
Backport PR #443 on branch 1.x (Add blocking signal feature)

### PR DESCRIPTION
**Pull request by fcollonval**
Backport PR #443

### CODE REVIEW

**Comment by krassowski** [comment]
I am not sure how significant this is, but it required us to update examples in JupyterLab because `block()`: is not optional (neither in main PR nor in backport): https://github.com/jupyterlab/jupyterlab/pull/13828/commits/6acbe4c5f7f5603a919bb8fa427673572d745468

**Comment by fcollonval** [comment]
There is at least one precedent of introduction a new API in 1.x: `Widget.hiddenMode` (see https://github.com/jupyterlab/lumino/commit/3d9e6256277b7c4b249e321f173d40f797bfe493#diff-1b48f924aeff3b4517f4629b461a839b4bac6fd745757e231b2b04a6055a00d9 ).

But as this one is at the end not used in JLab 3.6. I'm fine to do a patch release reverting this.

What do you think?

> Placing 3.6.0 release on hold due to this.

**Comment by krassowski** [comment]
Can `block` be made optional by addition of `?` in the interfaces?

**Comment by fcollonval** [comment]
I discussed with @afshin. We came up to the following conclusion:

As the `block` feature is not used (the goal was to use it for RTC improvements in 3.6.x - but finally it was possible to not use it):
- Revert the feature in Lumino 2
- Add a deprecation warning in Lumino 1 and make it optional (as you suggested)
  - Release a patch version of Lumino 1

**Comment by fcollonval** [comment]
I'll take care of those actions in Lumino

**Pull request merged**
