### PR TITLE
Fix ignored arrow keys

### LINKED ISSUE #255: Change in arrow keys handling broke contract
## Description

#252 broke navigation with arrow keys, selecting cells with arrow keys and all other operations using arrow keys in JupyterLab (which for now is only visible on JupyterLab Desktop https://github.com/jupyterlab/jupyterlab-desktop/issues/320). This is because the addition of:

https://github.com/jupyterlab/lumino/blob/0f7378b62338868a53d0e6418d333f7e718d7411/packages/commands/src/index.ts#L1138-L1145

means that:

https://github.com/jupyterlab/lumino/blob/0f7378b62338868a53d0e6418d333f7e718d7411/packages/commands/src/index.ts#L1146-L1148

will not be executed for arrow keys, and all existing logic that relayed on arrow keys being there will fail.

## Reproduce

See https://github.com/jupyterlab/jupyterlab-desktop/issues/320.

## Expected behavior

1) this was released in a minor version, so we should fix it quickly; we should not change the contract in minor versions
2) arrow keys are not proper modifiers and should not be excluded from `key`

### PR DESCRIPTION
**Pull request by krassowski**
Fixes #255

### CODE REVIEW

**Comment by krassowski** [comment]
The fix is good, but I also noted: https://github.com/jupyterlab/lumino/pull/252/files#r739683874 and will improve that as well here.

**Comment by krassowski** [comment]
@blink1073 would it be a good idea to add Mac to CI matrix, or was it purposefully excluded?

https://github.com/jupyterlab/lumino/blob/0f7378b62338868a53d0e6418d333f7e718d7411/.github/workflows/tests.yml#L10-L11

**Comment by jasongrout** [comment]
I added some more context and thoughts at https://github.com/jupyterlab/lumino/issues/151#issuecomment-955652297, since that seems like the best place to consolidate the conversation across #151, #252, #255, and #256.

**Comment by blink1073** [comment]
> @blink1073 would it be a good idea to add Mac to CI matrix, or was it purposefully excluded?

I don't remember the context at the time, but yes, we should be testing against Mac.

**Pull request closed without merging**
